// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7oWCot3SY0q71dapnGu-tqIAFzr1_6rE',
    appId: '1:1075672584307:android:ddd474973554aba4eb1a06',
    messagingSenderId: '1075672584307',
    projectId: 'smartai-d8cac',
    storageBucket: 'smartai-d8cac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWcct3zHQJ9gYVZHKhKgBYws5qBbSxtiE',
    appId: '1:1075672584307:ios:9964faf90169c8e8eb1a06',
    messagingSenderId: '1075672584307',
    projectId: 'smartai-d8cac',
    storageBucket: 'smartai-d8cac.appspot.com',
    androidClientId: '1075672584307-aj8vg5g1ambr3ol3ba33v1e0vpmftl14.apps.googleusercontent.com',
    iosClientId: '1075672584307-0b55ohl070cagr3u43543d18ln249po4.apps.googleusercontent.com',
    iosBundleId: 'com.halinhit.smartai',
  );

}